@echo off
echo Activating virtual environment...
call venv_new\Scripts\activate

echo Installing requirements...
pip install -r requirements.txt

echo Initializing database...
python init_db.py

echo Starting Flask application...
python run.py 